Asset Ops
UniqueNetwork/polkadot-sdk pull request #7
Opened 2024-04-24 11:18 UTC by mrshiposha

2024-04-24 12:36 UTC, CertainLach requested changes
Предварительно

Система типизированных атрибутов приятная, CanTransfer эти...
Но не совсем понятно как оно будет доступно пользователям рантайм типов (polkadot.js etc), полагается что каждый разработчик чейна сам реализует путь до типизированного атрибута от пользовательских запросов, в ядре никаких хелперов для этого не задумано?

2024-04-24 12:36 UTC, CertainLach commented on polkadot/xcm/xcm-builder/src/unique_instances.rs
> +pub struct TransferableInstanceAdapter<
Разнеси transferrable и recreatable на 2 файла лучше (оставив общую логику в этом)

2024-04-24 12:36 UTC, CertainLach commented on polkadot/xcm/xcm-executor/src/traits/token_matching.rs
> +		)* );
..Also, возможно стоит к следующему элементу переходить, только если текущий вернул AssetNotHandled?
На случай если кто-то намеренно будет возвращать другую ошибку, чтобы оно дальше не шло

2024-04-24 12:58 UTC, mrshiposha commented on substrate/frame/nfts/src/features/metadata.rs
> +		maybe_check_origin: Option<T::AccountId>,
Мне показалось, что лучше сделать как в других do_* функциях, чтобы не сильно выбивалось из общего ряда

2024-04-24 13:02 UTC, mrshiposha commented on polkadot/xcm/xcm-executor/src/traits/token_matching.rs
> +		)* );
Согласен, но я тут тоже старался не выделятся и сделал как в других матчерах.
Возможно стоит это тоже поправить, но как-то отдельным PR'ов и для всех матчеров сразу

2024-04-24 13:04 UTC, CertainLach commented on polkadot/xcm/xcm-executor/src/traits/token_matching.rs
> +		)* );
В других матчерах тоже `o @ Ok(_) => return o, _ => ()`  вместо простого if let?!
Отвратительно

2024-04-24 13:07 UTC, mrshiposha commented on substrate/frame/support/src/traits/tokens/asset_ops.rs
> +	pub struct CanTransfer<Flavor = ()>(pub Flavor);
>Но не совсем понятно как оно будет доступно пользователям рантайм типов (polkadot.js etc), полагается что каждый разработчик чейна сам реализует путь до типизированного атрибута от пользовательских запросов, в ядре никаких хелперов для этого не задумано?

Вообще говоря, эти трейты задуманы для взаимодействия между сущностями в рантайме. В том числе, чтобы для XCM адаптеров меньше вещей требовалось.

Если хочется JS интерфейс, то каждая отдельная реализация или чейн целиком должны свой JS интерфейс предоставить (конкретный, не абстрактный).

Возможно, это надо как-то прописать где-то.
Если же придумывать как это автоматизировано прокидывать в JS, то тут надо что-то серьезное. Это не входило в изначальную задумку.

2024-04-24 13:09 UTC, mrshiposha commented on substrate/frame/support/src/traits/tokens/asset_ops.rs
> +	pub struct CanTransfer<Flavor = ()>(pub Flavor);
В конце концов, текущие nonfungibles_v2 тоже в JS не прокидываются. Есть отдельный Runtime API, который повторяет некоторые методы

2024-04-24 13:10 UTC, CertainLach commented on substrate/frame/support/src/traits/tokens/asset_ops.rs
> +	pub struct CanTransfer<Flavor = ()>(pub Flavor);
Это окей, это я понимаю, лишь уточнил что это пока не планируется стандартизировать

2024-04-24 13:31 UTC, mrshiposha commented on polkadot/xcm/xcm-builder/src/unique_instances.rs
> +pub struct TransferableInstanceAdapter<
Разбил на 3 файла весь этот модуль

2024-04-25 11:27 UTC, CertainLach approved these changes
Кроме того что ошибки кроме AssetNotHandled идут дальше по матчеру, что мешает сделать потециально полезный матчер для short-circuit проверок, возвражений не имею

2024-04-25 11:30 UTC, CertainLach commented on substrate/frame/nft-fractionalization/src/lib.rs
> +				T::Nfts::inspect_metadata(&(nft_collection_id, nft_id), Ownership::new())?;
Хотя, для красоты бы завести NftsExt трейт, который с well-known атрибутами работает, чтобы не везде напрямую так делать)

2024-04-25 11:34 UTC, CertainLach commented on substrate/frame/support/src/traits/tokens/asset_ops.rs
> +		pub fn new() -> Self {
Можно заменить на derive(Default) + Default

2024-04-25 12:42 UTC, PraetorP approved these changes

2024-04-25 15:11 UTC, mrshiposha commented on substrate/frame/nft-fractionalization/src/lib.rs
> +				T::Nfts::inspect_metadata(&(nft_collection_id, nft_id), Ownership::new())?;
Может быть, но, наверное, я пока не буду этого делать. Если трейты в целом примут тепло, можно будет добавить. Боюсь дополнительные штуки вводить пока что

2024-04-25 17:27 UTC, closed without merging